wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.0
    framework: huggingface
    huggingface_version: 4.28.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690393372.07904
    t:
      1:
      - 1
      - 11
      - 30
      - 49
      - 51
      - 55
      - 71
      - 85
      2:
      - 1
      - 11
      - 30
      - 49
      - 51
      - 55
      - 71
      - 85
      3:
      - 13
      - 15
      - 23
      4: 3.8.10
      5: 0.15.0
      6: 4.28.1
      8:
      - 5
method:
  desc: null
  value:
    name: PPOConfig
    ppo_epochs: 4
    num_rollouts: 128
    chunk_size: 12
    init_kl_coef: 0.1
    target: 6
    horizon: 1000
    gamma: 0.99
    lam: 0.95
    cliprange: 0.2
    cliprange_value: 0.2
    vf_coef: 1
    scale_reward: null
    ref_mean: null
    ref_std: null
    cliprange_reward: 10
    gen_kwargs:
      max_new_tokens: 128
      do_sample: true
      top_k: 50
      top_p: 0.95
      eos_token_id: 1
      temperature: 1.0
    gen_experience_kwargs: null
model:
  desc: null
  value:
    model_path: /root/autodl-tmp/flan-t5-large
    model_arch_type: seq2seq
    num_layers_unfrozen: 2
    peft_config: null
optimizer:
  desc: null
  value:
    name: adamw
    kwargs:
      lr: 0.0001
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
      weight_decay: 1.0e-06
scheduler:
  desc: null
  value:
    name: cosine_annealing
    kwargs:
      T_max: 100000
      eta_min: 1.0e-06
tokenizer:
  desc: null
  value:
    tokenizer_path: /root/autodl-tmp/flan-t5-large
    padding_side: right
    truncation_side: right
train:
  desc: null
  value:
    total_steps: 6000
    seq_length: 512
    epochs: 100
    batch_size: 16
    checkpoint_interval: 1000
    eval_interval: 50
    pipeline: PromptPipeline
    trainer: AcceleratePPOTrainer
    trainer_kwargs: {}
    project_name: trlx
    entity_name: null
    group_name: null
    checkpoint_dir: /root/autodl-tmp/msc_ml/t5_large_checkpoints/navigate
    rollout_logging_dir: null
    save_best: false
    save_optimizer: true
    tracker: wandb
    logging_dir: null
    tags: []
    seed: 1000
    minibatch_size: null
distributed:
  desc: null
  value:
    mixed_precision: 'no'
    num_gpus: 1
